// Custom language selector: visible icon + custom dropdown, with hidden native <select> kept for compatibility.
// Populates the dropdown from the native select's options and syncs selection both ways.

// Completely generated by AI, i'm not smart enough to do this myself.

document.addEventListener('DOMContentLoaded', () => {
    const nativeSelect = document.getElementById('langSelector');
    const btn = document.getElementById('langSelectorBtn');
    const dropdown = document.getElementById('langDropdown');

    if (!nativeSelect || !btn || !dropdown) return;

    // Build dropdown items from native select
    function buildDropdown() {
        dropdown.innerHTML = '';
        Array.from(nativeSelect.options).forEach(opt => {
            const li = document.createElement('li');
            li.className = 'lang-option';
            li.setAttribute('role', 'option');
            li.dataset.value = opt.value;

            const codeSpan = document.createElement('span');
            codeSpan.className = 'lang-code';
            codeSpan.textContent = opt.value.toUpperCase();

            const labelSpan = document.createElement('span');
            labelSpan.className = 'lang-label';
            // use the option's visible text as label
            labelSpan.textContent = opt.text;

            li.appendChild(codeSpan);
            li.appendChild(labelSpan);

            // Mark selected
            if (nativeSelect.value === opt.value) li.classList.add('selected');

            li.addEventListener('click', (e) => {
                e.stopPropagation();
                selectLanguage(opt.value);
                closeDropdown();
                btn.focus();
            });

            dropdown.appendChild(li);
        });
    }

    function openDropdown() {
        dropdown.classList.add('open');
        btn.setAttribute('aria-expanded', 'true');
    }

    function closeDropdown() {
        dropdown.classList.remove('open');
        btn.setAttribute('aria-expanded', 'false');
    }

    function toggleDropdown() {
        if (dropdown.classList.contains('open')) closeDropdown();
        else openDropdown();
    }

    function selectLanguage(value) {
        if (nativeSelect.value === value) return;
        nativeSelect.value = value;
        // Dispatch a change event so existing scripts (translations.js etc.) react
        const ev = new Event('change', { bubbles: true });
        nativeSelect.dispatchEvent(ev);
        updateSelectedUI();
    }

    function updateSelectedUI() {
        const items = dropdown.querySelectorAll('.lang-option');
        items.forEach(it => {
            if (it.dataset.value === nativeSelect.value) it.classList.add('selected');
            else it.classList.remove('selected');
        });
    }

    // Close when clicking outside
    document.addEventListener('click', (e) => {
        if (!e.target.closest('.lang-selector')) {
            closeDropdown();
        }
    });

    // Keyboard support for button
    btn.addEventListener('keydown', (e) => {
        if (e.key === 'ArrowDown' || e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            openDropdown();
            // focus first item
            const first = dropdown.querySelector('.lang-option');
            if (first) first.focus();
        } else if (e.key === 'Escape') {
            closeDropdown();
        }
    });

    // Make list items focusable
    dropdown.addEventListener('keydown', (e) => {
        const focused = document.activeElement;
        if (!focused || !focused.classList.contains('lang-option')) return;
        if (e.key === 'ArrowDown') {
            e.preventDefault();
            const next = focused.nextElementSibling;
            if (next) next.focus();
        } else if (e.key === 'ArrowUp') {
            e.preventDefault();
            const prev = focused.previousElementSibling;
            if (prev) prev.focus();
        } else if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            selectLanguage(focused.dataset.value);
            closeDropdown();
            btn.focus();
        } else if (e.key === 'Escape') {
            closeDropdown();
            btn.focus();
        }
    });

    // Make li elements focusable when built
    function makeItemsFocusable() {
        const items = dropdown.querySelectorAll('.lang-option');
        items.forEach(it => {
            it.tabIndex = 0;
        });
    }

    // Sync UI when native select changes (maybe changed elsewhere)
    nativeSelect.addEventListener('change', () => {
        updateSelectedUI();
    });

    // Button toggles dropdown
    btn.addEventListener('click', (e) => {
        e.stopPropagation();
        toggleDropdown();
        // focus first item if opening
        if (dropdown.classList.contains('open')) {
            const first = dropdown.querySelector('.lang-option');
            if (first) first.focus();
        }
    });

    // Initial build and sync
    buildDropdown();
    makeItemsFocusable();
    updateSelectedUI();
});
