// Song database
const songsDatabase = [
    {
        id: 1,
        title: "Kesäyö",
        artist: "Matti Virtanen",
        year: 2018,
        level: "beginner",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        lyrics: [
            { finnish: "Kesäyö on kaunis", english: "Summer night is beautiful", spanish: "La noche de verano es hermosa", french: "La nuit d'été est belle", arabic: "ليلة الصيف جميلة", dutch: "Zomernacht is mooi", time: 0 },
            { finnish: "Tähdet loistaa kirkkaasti", english: "Stars shine brightly", spanish: "Las estrellas brillan intensamente", french: "Les étoiles brillent vivement", arabic: "النجوم تتلألأ بشدة", dutch: "Sterren schijnen helder", time: 8 },
            { finnish: "Kuljen metsäpolkuja", english: "I walk forest paths", spanish: "Camino por senderos del bosque", french: "Je marche sur les sentiers forestiers", arabic: "أمشي على مسارات الغابة", dutch: "Ik wandel bospaden", time: 16 },
            { finnish: "Sydän täynnä iloa", english: "Heart full of joy", spanish: "Corazón lleno de alegría", french: "Cœur plein de joie", arabic: "قلب مليء بالفرح", dutch: "Hart vol vreugde", time: 24 },
            { finnish: "Yö on hiljainen ja rauhallinen", english: "Night is quiet and peaceful", spanish: "La noche es tranquila y pacífica", french: "La nuit est calme et paisible", arabic: "الليل هادئ وسلمي", dutch: "Nacht is stil en vredig", time: 32 },
            { finnish: "Kuulen vain luonnon äänet", english: "I hear only nature's sounds", spanish: "Solo escucho los sonidos de la naturaleza", french: "J'entends seulement les sons de la nature", arabic: "أسمع فقط أصوات الطبيعة", dutch: "Ik hoor alleen geluiden van de natuur", time: 40 },
            { finnish: "Tämä hetki on täydellinen", english: "This moment is perfect", spanish: "Este momento es perfecto", french: "Ce moment est parfait", arabic: "هذه اللحظة مثالية", dutch: "Dit moment is perfect", time: 48 },
            { finnish: "En halua että se loppuu", english: "I don't want it to end", spanish: "No quiero que termine", french: "Je ne veux pas que ça finisse", arabic: "لا أريد أن تنتهي", dutch: "Ik wil niet dat het eindigt", time: 56 },
            { finnish: "Tuuli tuoksuu raikkaalta", english: "Wind smells fresh", spanish: "El viento huele fresco", french: "Le vent sent frais", arabic: "الريح رائحتها منعشة", dutch: "Wind ruikt fris", time: 64 },
            { finnish: "Kesä on ihanaa aikaa", english: "Summer is wonderful time", spanish: "El verano es un tiempo maravilloso", french: "L'été est une période merveilleuse", arabic: "الصيف وقت رائع", dutch: "Zomer is een heerlijke tijd", time: 72 }
        ]
    },
    {
        id: 2,
        title: "Satumaa",
        artist: "Anna Korhonen",
        year: 2015,
        level: "beginner",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        lyrics: [
            { finnish: "Satumaa, satumaa", english: "Fairyland, fairyland", spanish: "Tierra de cuento, tierra de cuento", french: "Pays des contes, pays des contes", arabic: "أرض الخيال، أرض الخيال", dutch: "Sprookjesland, sprookjesland", time: 0 },
            { finnish: "Kaunehin ja ihanin", english: "Most beautiful and wonderful", spanish: "La más hermosa y maravillosa", french: "La plus belle et merveilleuse", arabic: "الأجمل والأروع", dutch: "Mooiste en prachtigste", time: 7 },
            { finnish: "Sinne matkaan tahtoisin", english: "There I would like to travel", spanish: "Allí me gustaría viajar", french: "J'aimerais y voyager", arabic: "أود السفر إلى هناك", dutch: "Daar zou ik naartoe willen reizen", time: 14 },
            { finnish: "Yli meren sinisen", english: "Over the blue sea", spanish: "Sobre el mar azul", french: "Par-dessus la mer bleue", arabic: "فوق البحر الأزرق", dutch: "Over de blauwe zee", time: 21 },
            { finnish: "Missä kaikki on kaunista", english: "Where everything is beautiful", spanish: "Donde todo es hermoso", french: "Où tout est beau", arabic: "حيث كل شيء جميل", dutch: "Waar alles mooi is", time: 28 },
            { finnish: "Ja ihmiset ovat onnellisia", english: "And people are happy", spanish: "Y la gente es feliz", french: "Et les gens sont heureux", arabic: "والناس سعداء", dutch: "En mensen zijn gelukkig", time: 35 },
            { finnish: "Haaveilen sinusta joka päivä", english: "I dream of you every day", spanish: "Sueño contigo cada día", french: "Je rêve de toi chaque jour", arabic: "أحلم بك كل يوم", dutch: "Ik droom elke dag van je", time: 42 },
            { finnish: "Jonain päivänä pääsen sinne", english: "Someday I will get there", spanish: "Algún día llegaré allí", french: "Un jour j'y arriverai", arabic: "يوماً ما سأصل إلى هناك", dutch: "Op een dag kom ik daar", time: 49 },
            { finnish: "Satumaa odottaa minua", english: "Fairyland waits for me", spanish: "La tierra de cuento me espera", french: "Le pays des contes m'attend", arabic: "أرض الخيال تنتظرني", dutch: "Sprookjesland wacht op mij", time: 56 },
            { finnish: "Se on täydellinen paikka", english: "It is a perfect place", spanish: "Es un lugar perfecto", french: "C'est un endroit parfait", arabic: "إنه مكان مثالي", dutch: "Het is een perfecte plek", time: 63 }
        ]
    },
    {
        id: 3,
        title: "Kotikaupunkini",
        artist: "Mikko Salo",
        year: 2016,
        level: "intermediate",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        lyrics: [
            { finnish: "Tämä on kotikaupunkini", english: "This is my hometown", spanish: "Esta es mi ciudad natal", french: "C'est ma ville natale", arabic: "هذه مدينتي", dutch: "Dit is mijn geboortestad", time: 0 },
            { finnish: "Tunnen jokaisen kadun", english: "I know every street", spanish: "Conozco cada calle", french: "Je connais chaque rue", arabic: "أعرف كل شارع", dutch: "Ik ken elke straat", time: 6 },
            { finnish: "Muistot täyttää sydämen", english: "Memories fill the heart", spanish: "Los recuerdos llenan el corazón", french: "Les souvenirs remplissent le cœur", arabic: "الذكريات تملأ القلب", dutch: "Herinneringen vullen het hart", time: 12 },
            { finnish: "Täällä aina palaan", english: "Here I always return", spanish: "Aquí siempre regreso", french: "Ici je reviens toujours", arabic: "هنا أعود دائماً", dutch: "Hier keer ik altijd terug", time: 18 },
            { finnish: "Lapsuuteni talot seisovat vielä", english: "My childhood houses still stand", spanish: "Las casas de mi infancia aún permanecen", french: "Les maisons de mon enfance sont toujours là", arabic: "منازل طفولتي لا تزال قائمة", dutch: "De huizen van mijn jeugd staan er nog", time: 24 },
            { finnish: "Ystäväni asuvat lähellä", english: "My friends live nearby", spanish: "Mis amigos viven cerca", french: "Mes amis vivent à proximité", arabic: "أصدقائي يعيشون قريباً", dutch: "Mijn vrienden wonen dichtbij", time: 30 },
            { finnish: "Tämä paikka on minun kotini", english: "This place is my home", spanish: "Este lugar es mi hogar", french: "Cet endroit est ma maison", arabic: "هذا المكان هو بيتي", dutch: "Deze plek is mijn thuis", time: 36 },
            { finnish: "En vaihda sitä mihinkään", english: "I wouldn't trade it for anything", spanish: "No lo cambiaría por nada", french: "Je ne l'échangerais pour rien", arabic: "لن أبادله بأي شيء", dutch: "Ik zou het voor niets ruilen", time: 42 },
            { finnish: "Joka nurkan takana on tarina", english: "Behind every corner is a story", spanish: "Detrás de cada esquina hay una historia", french: "Derrière chaque coin il y a une histoire", arabic: "خلف كل زاوية قصة", dutch: "Achter elke hoek is een verhaal", time: 48 },
            { finnish: "Puistossa leikimme lapsena", english: "We played in the park as children", spanish: "Jugábamos en el parque de niños", french: "Nous jouions dans le parc enfants", arabic: "لعبنا في الحديقة كأطفال", dutch: "We speelden in het park als kinderen", time: 54 },
            { finnish: "Koulun piha näyttää pienemmältä nyt", english: "The schoolyard looks smaller now", spanish: "El patio de la escuela se ve más pequeño ahora", french: "La cour d'école semble plus petite maintenant", arabic: "ساحة المدرسة تبدو أصغر الآن", dutch: "Het schoolplein ziet er nu kleiner uit", time: 60 },
            { finnish: "Mutta tunteet ovat samat", english: "But the feelings are the same", spanish: "Pero los sentimientos son los mismos", french: "Mais les sentiments sont les mêmes", arabic: "لكن المشاعر هي نفسها", dutch: "Maar de gevoelens zijn hetzelfde", time: 66 },
            { finnish: "Kesäisin kävelemme rantaan", english: "In summers we walk to the beach", spanish: "En verano caminamos a la playa", french: "En été nous marchons vers la plage", arabic: "في الصيف نمشي إلى الشاطئ", dutch: "In de zomer lopen we naar het strand", time: 72 },
            { finnish: "Talvisin luistelemme jäällä", english: "In winters we skate on ice", spanish: "En invierno patinamos sobre hielo", french: "En hiver nous patinons sur la glace", arabic: "في الشتاء نتزلج على الجليد", dutch: "In de winter schaatsen we op het ijs", time: 78 },
            { finnish: "Vuodenajat vaihtuvat", english: "Seasons change", spanish: "Las estaciones cambian", french: "Les saisons changent", arabic: "المواسم تتغير", dutch: "Seizoenen veranderen", time: 84 },
            { finnish: "Mutta kaupunki pysyy samana", english: "But the city stays the same", spanish: "Pero la ciudad permanece igual", french: "Mais la ville reste la même", arabic: "لكن المدينة تبقى كما هي", dutch: "Maar de stad blijft hetzelfde", time: 90 },
            { finnish: "Se on osa identiteettiäni", english: "It is part of my identity", spanish: "Es parte de mi identidad", french: "C'est une partie de mon identité", arabic: "إنها جزء من هويتي", dutch: "Het is een deel van mijn identiteit", time: 96 },
            { finnish: "Kantamassa mukanani kaikkialle", english: "Carrying with me everywhere", spanish: "Llevándola conmigo a todas partes", french: "La portant avec moi partout", arabic: "أحملها معي في كل مكان", dutch: "Het overal met me meedragen", time: 102 },
            { finnish: "Kun matkan päälle lähden", english: "When I set out to travel", spanish: "Cuando me pongo en viaje", french: "Quand je pars en voyage", arabic: "عندما أبدأ السفر", dutch: "Wanneer ik op reis ga", time: 108 },
            { finnish: "Kaipaan aina takaisin", english: "I always miss coming back", spanish: "Siempre extraño volver", french: "Je regrette toujours de revenir", arabic: "أشتاق دائماً للعودة", dutch: "Ik verlang altijd naar terugkomen", time: 114 },
            { finnish: "Kotikaupunkini kutsuu", english: "My hometown calls", spanish: "Mi ciudad natal llama", french: "Ma ville natale appelle", arabic: "مدينتي تناديني", dutch: "Mijn geboortestad roept", time: 120 },
            { finnish: "Sen rauha ja lämpö", english: "Its peace and warmth", spanish: "Su paz y calidez", french: "Sa paix et sa chaleur", arabic: "سلامها ودفؤها", dutch: "Haar vrede en warmte", time: 126 },
            { finnish: "Tutut kasvot kadulla", english: "Familiar faces on the street", spanish: "Caras familiares en la calle", french: "Des visages familiers dans la rue", arabic: "وجوه مألوفة في الشارع", dutch: "Vertrouwde gezichten op straat", time: 132 },
            { finnish: "Tervehdykset ja hymyt", english: "Greetings and smiles", spanish: "Saludos y sonrisas", french: "Salutations et sourires", arabic: "التحيات والابتسامات", dutch: "Begroetingen en glimlachen", time: 138 },
            { finnish: "Tämä on minun paikkani", english: "This is my place", spanish: "Este es mi lugar", french: "C'est mon endroit", arabic: "هذا مكاني", dutch: "Dit is mijn plek", time: 144 },
            { finnish: "Täällä kuulun", english: "Here I belong", spanish: "Aquí pertenezco", french: "Ici j'appartiens", arabic: "هنا أنتمي", dutch: "Hier hoor ik thuis", time: 150 },
            { finnish: "Täällä olen kotona", english: "Here I am home", spanish: "Aquí estoy en casa", french: "Ici je suis chez moi", arabic: "هنا أنا في بيتي", dutch: "Hier ben ik thuis", time: 156 },
            { finnish: "Kotikaupunkini, rakas kaupunkini", english: "My hometown, my dear city", spanish: "Mi ciudad natal, mi querida ciudad", french: "Ma ville natale, ma chère ville", arabic: "مدينتي، مدينتي العزيزة", dutch: "Mijn geboortestad, mijn lieve stad", time: 162 },
            { finnish: "Ikuisesti sydämessäni", english: "Forever in my heart", spanish: "Por siempre en mi corazón", french: "Pour toujours dans mon cœur", arabic: "إلى الأبد في قلبي", dutch: "Voor altijd in mijn hart", time: 168 },
            { finnish: "Tämä on minun tarinani", english: "This is my story", spanish: "Esta es mi historia", french: "C'est mon histoire", arabic: "هذه قصتي", dutch: "Dit is mijn verhaal", time: 174 }
        ]
    },
    {
        id: 4,
        title: "Syksy saapuu",
        artist: "Sanna Heikkinen",
        year: 2019,
        level: "intermediate",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        lyrics: [
            { finnish: "Lehdet putoaa maahan", english: "Leaves fall to the ground", spanish: "Las hojas caen al suelo", french: "Les feuilles tombent au sol", arabic: "الأوراق تسقط على الأرض", dutch: "Bladeren vallen op de grond", time: 0 },
            { finnish: "Värit vaihtuvat kultaan", english: "Colors change to gold", spanish: "Los colores cambian a oro", french: "Les couleurs changent en or", arabic: "الألوان تتحول إلى ذهبي", dutch: "Kleuren veranderen in goud", time: 6 },
            { finnish: "Tuuli humisee puissa", english: "Wind whispers in the trees", spanish: "El viento susurra en los árboles", french: "Le vent murmure dans les arbres", arabic: "الريح تهمس في الأشجار", dutch: "De wind fluistert in de bomen", time: 12 },
            { finnish: "Syksy on saapunut", english: "Autumn has arrived", spanish: "El otoño ha llegado", french: "L'automne est arrivé", arabic: "وصل الخريف", dutch: "De herfst is aangekomen", time: 18 },
            { finnish: "Ilma muuttuu viileämmäksi", english: "The air becomes cooler", spanish: "El aire se vuelve más fresco", french: "L'air devient plus frais", arabic: "الهواء يصبح أبرد", dutch: "De lucht wordt koeler", time: 24 },
            { finnish: "Päivät lyhenevät nopeasti", english: "Days shorten quickly", spanish: "Los días se acortan rápidamente", french: "Les jours raccourcissent rapidement", arabic: "الأيام تقصر بسرعة", dutch: "Dagen worden snel korter", time: 30 },
            { finnish: "Luonto valmistautuu talveen", english: "Nature prepares for winter", spanish: "La naturaleza se prepara para el invierno", french: "La nature se prépare pour l'hiver", arabic: "الطبيعة تستعد للشتاء", dutch: "De natuur bereidt zich voor op de winter", time: 36 },
            { finnish: "Mutta kauneus on kaikkialla", english: "But beauty is everywhere", spanish: "Pero la belleza está en todas partes", french: "Mais la beauté est partout", arabic: "لكن الجمال في كل مكان", dutch: "Maar schoonheid is overal", time: 42 },
            { finnish: "Punainen, oranssi ja keltainen", english: "Red, orange and yellow", spanish: "Rojo, naranja y amarillo", french: "Rouge, orange et jaune", arabic: "أحمر وبرتقالي وأصفر", dutch: "Rood, oranje en geel", time: 48 },
            { finnish: "Väriloisto ympärilläni", english: "Blaze of colors around me", spanish: "Resplandor de colores a mi alrededor", french: "Éclat de couleurs autour de moi", arabic: "وهج الألوان من حولي", dutch: "Kleurenpracht om me heen", time: 54 },
            { finnish: "Metsä näyttää maalaukset", english: "Forest looks like a painting", spanish: "El bosque parece una pintura", french: "La forêt ressemble à une peinture", arabic: "الغابة تبدو كلوحة", time: 60 },
            { finnish: "Luonnon taideteos", english: "Nature's artwork", spanish: "Obra de arte de la naturaleza", french: "Œuvre d'art de la nature", arabic: "عمل فني للطبيعة", time: 66 },
            { finnish: "Sade piiskainen ikkunaan", english: "Rain lashes against the window", spanish: "La lluvia azota la ventana", french: "La pluie fouette la fenêtre", arabic: "المطر يضرب النافذة", time: 72 },
            { finnish: "Harmaa taivas peittää kaiken", english: "Gray sky covers everything", spanish: "El cielo gris cubre todo", french: "Le ciel gris couvre tout", arabic: "السماء الرمادية تغطي كل شيء", time: 78 },
            { finnish: "Mutta minä rakastan syksyä", english: "But I love autumn", spanish: "Pero amo el otoño", french: "Mais j'aime l'automne", arabic: "لكنني أحب الخريف", time: 84 },
            { finnish: "Sen melankolinen kauneus", english: "Its melancholic beauty", spanish: "Su belleza melancólica", french: "Sa beauté mélancolique", arabic: "جماله الكئيب", time: 90 },
            { finnish: "Sateenvarjo kädessäni", english: "Umbrella in my hand", spanish: "Paraguas en mi mano", french: "Parapluie à la main", arabic: "مظلة في يدي", time: 96 },
            { finnish: "Kävelen läpi kaupungin", english: "I walk through the city", spanish: "Camino por la ciudad", french: "Je marche à travers la ville", arabic: "أمشي عبر المدينة", time: 102 },
            { finnish: "Lätäköt heijastaa valoja", english: "Puddles reflect lights", spanish: "Los charcos reflejan luces", french: "Les flaques reflètent les lumières", arabic: "البرك تعكس الأضواء", time: 108 },
            { finnish: "Autot ajavat hitaasti", english: "Cars drive slowly", spanish: "Los coches conducen lentamente", french: "Les voitures roulent lentement", arabic: "السيارات تقود ببطء", time: 114 },
            { finnish: "Ihmiset kiiruhtavat sisälle", english: "People hurry inside", spanish: "La gente se apresura adentro", french: "Les gens se dépêchent à l'intérieur", arabic: "الناس يسرعون للداخل", dutch: "Mensen haasten zich naar binnen", time: 120 },
            { finnish: "Mutta minä nautin hetkestä", english: "But I enjoy the moment", spanish: "Pero disfruto el momento", french: "Mais je profite du moment", arabic: "لكنني أستمتع باللحظة", dutch: "Maar ik geniet van het moment", time: 126 },
            { finnish: "Kylmä tuuli poskillani", english: "Cold wind on my cheeks", spanish: "Viento frío en mis mejillas", french: "Vent froid sur mes joues", arabic: "الريح الباردة على خدودي", dutch: "Koude wind op mijn wangen", time: 132 },
            { finnish: "Elossa tunnen olevani", english: "I feel alive", spanish: "Me siento vivo", french: "Je me sens vivant", arabic: "أشعر بالحياة", dutch: "Ik voel me levend", time: 138 },
            { finnish: "Syksy opettaa arvostamaan", english: "Autumn teaches to appreciate", spanish: "El otoño enseña a apreciar", french: "L'automne enseigne à apprécier", arabic: "الخريف يعلم التقدير", dutch: "De herfst leert waarderen", time: 144 },
            { finnish: "Jokaista vuodenaikaa", english: "Every season", spanish: "Cada estación", french: "Chaque saison", arabic: "كل موسم", dutch: "Elk seizoen", time: 150 },
            { finnish: "Muutosta ja uudistumista", english: "Change and renewal", spanish: "Cambio y renovación", french: "Changement et renouveau", arabic: "التغيير والتجديد", dutch: "Verandering en vernieuwing", time: 156 },
            { finnish: "Elämän sykliä", english: "The cycle of life", spanish: "El ciclo de la vida", french: "Le cycle de la vie", arabic: "دورة الحياة", dutch: "De cyclus van het leven", time: 162 },
            { finnish: "Pian tulee talvi", english: "Soon winter will come", spanish: "Pronto llegará el invierno", french: "Bientôt l'hiver viendra", arabic: "قريباً سيأتي الشتاء", dutch: "Binnenkort komt de winter", time: 168 },
            { finnish: "Mutta nyt on syksy", english: "But now it's autumn", spanish: "Pero ahora es otoño", french: "Mais maintenant c'est l'automne", arabic: "لكن الآن هو الخريف", dutch: "Maar nu is het herfst", time: 174 }
        ]
    },
    {
        id: 5,
        title: "Elämän polku",
        artist: "Henrik Laine",
        year: 2017,
        level: "advanced",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
        lyrics: [
            { finnish: "Kulkiessani elämän polkua", english: "As I walk life's path", spanish: "Mientras camino por el sendero de la vida", french: "En marchant sur le chemin de la vie", arabic: "بينما أسير على مسار الحياة", dutch: "Terwijl ik het pad van het leven bewandel", time: 0 },
            { finnish: "Kohtaan monia haasteita", english: "I face many challenges", spanish: "Enfrento muchos desafíos", french: "Je fais face à de nombreux défis", arabic: "أواجه العديد من التحديات", dutch: "Sta ik voor veel uitdagingen", time: 5 },
            { finnish: "Jokainen askel opettaa", english: "Every step teaches", spanish: "Cada paso enseña", french: "Chaque pas enseigne", arabic: "كل خطوة تعلم", dutch: "Elke stap leert", time: 10 },
            { finnish: "Viisautta ja ymmärrystä", english: "Wisdom and understanding", spanish: "Sabiduría y comprensión", french: "Sagesse et compréhension", arabic: "الحكمة والفهم", dutch: "Wijsheid en begrip", time: 15 },
            { finnish: "Virheistä opin eniten", english: "I learn most from mistakes", spanish: "Aprendo más de los errores", french: "J'apprends le plus des erreurs", arabic: "أتعلم أكثر من الأخطاء", dutch: "Ik leer het meest van fouten", time: 20 },
            { finnish: "Onnistumiset antavat voimaa", english: "Successes give strength", spanish: "Los éxitos dan fuerza", french: "Les succès donnent de la force", arabic: "النجاحات تعطي القوة", dutch: "Successen geven kracht", time: 25 },
            { finnish: "Matka on tärkeämpi kuin määränpää", english: "Journey is more important than destination", spanish: "El viaje es más importante que el destino", french: "Le voyage est plus important que la destination", arabic: "الرحلة أهم من الوجهة", dutch: "De reis is belangrijker dan de bestemming", time: 30 },
            { finnish: "Elämä on kaunis kokemus", english: "Life is a beautiful experience", spanish: "La vida es una experiencia hermosa", french: "La vie est une belle expérience", arabic: "الحياة تجربة جميلة", dutch: "Het leven is een mooie ervaring", time: 35 },
            { finnish: "Joskus polku on kivikkoinen", english: "Sometimes the path is rocky", spanish: "A veces el camino es rocoso", french: "Parfois le chemin est rocheux", arabic: "أحياناً يكون المسار صخرياً", dutch: "Soms is het pad rotsachtig", time: 40 },
            { finnish: "Toisinaan se on sileä ja helppo", english: "Other times it's smooth and easy", spanish: "Otras veces es suave y fácil", french: "D'autres fois il est lisse et facile", arabic: "في أوقات أخرى يكون ناعماً وسهلاً", dutch: "Andere keren is het glad en gemakkelijk", time: 45 },
            { finnish: "Molemmat opettavat jotain tärkeää", english: "Both teach something important", spanish: "Ambos enseñan algo importante", french: "Les deux enseignent quelque chose d'important", arabic: "كلاهما يعلم شيئاً مهماً", dutch: "Beide leren iets belangrijks", time: 50 },
            { finnish: "Vastustus kasvattaa voimaa", english: "Resistance builds strength", spanish: "La resistencia construye fuerza", french: "La résistance construit la force", arabic: "المقاومة تبني القوة", dutch: "Weerstand bouwt kracht op", time: 55 },
            { finnish: "Pettymykset kehittävät sinnikkyyttä", english: "Disappointments develop perseverance", spanish: "Las decepciones desarrollan perseverancia", french: "Les déceptions développent la persévérance", arabic: "خيبات الأمل تطور المثابرة", dutch: "Teleurstellingen ontwikkelen doorzettingsvermogen", time: 60 },
            { finnish: "Ilo vahvistaa toivoa", english: "Joy strengthens hope", spanish: "La alegría fortalece la esperanza", french: "La joie renforce l'espoir", arabic: "الفرح يقوي الأمل", dutch: "Vreugde versterkt hoop", time: 65 },
            { finnish: "Rakkaus antaa merkityksen", english: "Love gives meaning", spanish: "El amor da significado", french: "L'amour donne un sens", arabic: "الحب يعطي المعنى", dutch: "Liefde geeft betekenis", time: 70 },
            { finnish: "Ystävyys tukee vaikeina aikoina", english: "Friendship supports in difficult times", spanish: "La amistad apoya en tiempos difíciles", french: "L'amitié soutient dans les moments difficiles", arabic: "الصداقة تدعم في الأوقات الصعبة", dutch: "Vriendschap steunt in moeilijke tijden", time: 75 },
            { finnish: "Yksinäisyys opettaa itsetuntemusta", english: "Solitude teaches self-knowledge", spanish: "La soledad enseña autoconocimiento", french: "La solitude enseigne la connaissance de soi", arabic: "العزلة تعلم معرفة الذات", dutch: "Eenzaamheid leert zelfkennis", time: 80 },
            { finnish: "Yhteisöllisyys muistuttaa kuulumisesta", english: "Community reminds of belonging", spanish: "La comunidad recuerda la pertenencia", french: "La communauté rappelle l'appartenance", arabic: "المجتمع يذكر بالانتماء", dutch: "Gemeenschap herinnert aan erbij horen", time: 85 },
            { finnish: "Jokaisella kohtaamisella on tarkoitus", english: "Every encounter has a purpose", spanish: "Cada encuentro tiene un propósito", french: "Chaque rencontre a un but", arabic: "كل لقاء له هدف", dutch: "Elke ontmoeting heeft een doel", time: 90 },
            { finnish: "Jokaisella kokemuksella on opetus", english: "Every experience has a lesson", spanish: "Cada experiencia tiene una lección", french: "Chaque expérience a une leçon", arabic: "كل تجربة لها درس", dutch: "Elke ervaring heeft een les", time: 95 },
            { finnish: "En tiedä minne polku vie", english: "I don't know where the path leads", spanish: "No sé a dónde lleva el camino", french: "Je ne sais pas où mène le chemin", arabic: "لا أعرف إلى أين يؤدي المسار", dutch: "Ik weet niet waar het pad leidt", time: 100 },
            { finnish: "Mutta luotan prosessiin", english: "But I trust the process", spanish: "Pero confío en el proceso", french: "Mais je fais confiance au processus", arabic: "لكنني أثق بالعملية", dutch: "Maar ik vertrouw op het proces", time: 105 },
            { finnish: "Hyväksyn epävarmuuden", english: "I accept uncertainty", spanish: "Acepto la incertidumbre", french: "J'accepte l'incertitude", arabic: "أقبل عدم اليقين", dutch: "Ik accepteer onzekerheid", time: 110 },
            { finnish: "Nautin matkasta", english: "I enjoy the journey", spanish: "Disfruto del viaje", french: "Je profite du voyage", arabic: "أستمتع بالرحلة", dutch: "Ik geniet van de reis", time: 115 },
            { finnish: "Arviostan jokaista hetkeä", english: "I appreciate every moment", spanish: "Aprecio cada momento", french: "J'apprécie chaque moment", arabic: "أقدر كل لحظة", dutch: "Ik waardeer elk moment", time: 120 },
            { finnish: "Hyvää ja pahaa", english: "Good and bad", spanish: "Bueno y malo", french: "Bon et mauvais", arabic: "الخير والشر", dutch: "Goed en slecht", time: 125 },
            { finnish: "Iloa ja surua", english: "Joy and sorrow", spanish: "Alegría y tristeza", french: "Joie et tristesse", arabic: "الفرح والحزن", dutch: "Vreugde en verdriet", time: 130 },
            { finnish: "Voittoja ja tappioita", english: "Wins and losses", spanish: "Victorias y derrotas", french: "Victoires et défaites", arabic: "انتصارات وخسائر", dutch: "Overwinningen en verliezen", time: 135 },
            { finnish: "Kaikki on osa tarinaa", english: "Everything is part of the story", spanish: "Todo es parte de la historia", french: "Tout fait partie de l'histoire", arabic: "كل شيء جزء من القصة", dutch: "Alles is deel van het verhaal", time: 140 },
            { finnish: "Minun ainutlaatuista tarinaani", english: "My unique story", spanish: "Mi historia única", french: "Mon histoire unique", arabic: "قصتي الفريدة", dutch: "Mijn unieke verhaal", time: 145 },
            { finnish: "Kerron sitä joka päivä", english: "I tell it every day", spanish: "La cuento cada día", french: "Je la raconte chaque jour", arabic: "أرويها كل يوم", dutch: "Ik vertel het elke dag", time: 150 },
            { finnish: "Valinnoillani ja teoillani", english: "With my choices and actions", spanish: "Con mis elecciones y acciones", french: "Avec mes choix et actions", arabic: "بخياراتي وأفعالي", dutch: "Met mijn keuzes en daden", time: 155 },
            { finnish: "Sanoin ja hiljaisuudella", english: "With words and silence", spanish: "Con palabras y silencio", french: "Avec des mots et du silence", arabic: "بالكلمات والصمت", dutch: "Met woorden en stilte", time: 160 },
            { finnish: "Rakkaudella ja anteeksiannolla", english: "With love and forgiveness", spanish: "Con amor y perdón", french: "Avec amour et pardon", arabic: "بالحب والمغفرة", dutch: "Met liefde en vergeving", time: 165 },
            { finnish: "Rohkeudella ja nöyryydellä", english: "With courage and humility", spanish: "Con valentía y humildad", french: "Avec courage et humilité", arabic: "بالشجاعة والتواضع", dutch: "Met moed en nederigheid", time: 170 },
            { finnish: "Elämän polku jatkuu", english: "Life's path continues", spanish: "El camino de la vida continúa", french: "Le chemin de la vie continue", arabic: "مسار الحياة يستمر", dutch: "Het levenspad gaat door", time: 175 },
            { finnish: "Niin kauan kuin hengitän", english: "As long as I breathe", spanish: "Mientras respire", french: "Tant que je respire", arabic: "طالما أنا أتنفس", dutch: "Zolang ik adem", time: 180 },
            { finnish: "Niin kauan kuin sydämeni sykkii", english: "As long as my heart beats", spanish: "Mientras mi corazón late", french: "Tant que mon cœur bat", arabic: "طالما قلبي ينبض", dutch: "Zolang mijn hart klopt", time: 185 },
            { finnish: "Niin kauan kuin unelmoin", english: "As long as I dream", spanish: "Mientras sueñe", french: "Tant que je rêve", arabic: "طالما أحلم", dutch: "Zolang ik droom", time: 190 },
            { finnish: "Polku on minun", english: "The path is mine", spanish: "El camino es mío", french: "Le chemin est le mien", arabic: "المسار ملكي", dutch: "Het pad is van mij", time: 195 },
            { finnish: "Vastuullani ja ilonani", english: "My responsibility and joy", spanish: "Mi responsabilidad y alegría", french: "Ma responsabilité et ma joie", arabic: "مسؤوليتي وفرحي", dutch: "Mijn verantwoordelijkheid en vreugde", time: 200 },
            { finnish: "Haasteenani ja lahjana", english: "My challenge and gift", spanish: "Mi desafío y regalo", french: "Mon défi et cadeau", arabic: "تحديي وهديتي", dutch: "Mijn uitdaging en geschenk", time: 205 },
            { finnish: "Kulkien sitä päivä kerrallaan", english: "Walking it one day at a time", spanish: "Caminándolo un día a la vez", french: "Le marchant un jour à la fois", arabic: "أسير عليه يوماً بيوم", dutch: "Het dag voor dag bewandelend", time: 210 },
            { finnish: "Askel askeleelta", english: "Step by step", spanish: "Paso a paso", french: "Pas à pas", arabic: "خطوة بخطوة", dutch: "Stap voor stap", time: 215 },
            { finnish: "Hengitys hengi tykseltä", english: "Breath by breath", spanish: "Respiración por respiración", french: "Souffle par souffle", arabic: "نفساً بنفس", dutch: "Ademhaling voor ademhaling", time: 220 },
            { finnish: "Hetki hetkeltä", english: "Moment by moment", spanish: "Momento a momento", french: "Moment par moment", arabic: "لحظة بلحظة", dutch: "Moment voor moment", time: 225 },
            { finnish: "Tämä on elämäni polku", english: "This is my life's path", spanish: "Este es el camino de mi vida", french: "C'est le chemin de ma vie", arabic: "هذا مسار حياتي", dutch: "Dit is mijn levenspad", time: 230 },
            { finnish: "Ja minä kävelen sitä ylpeänä", english: "And I walk it proudly", spanish: "Y lo camino con orgullo", french: "Et je le marche fièrement", arabic: "وأسير عليه بفخر", dutch: "En ik bewandel het met trots", time: 235 },
            { finnish: "Kiitollisena", english: "Gratefully", spanish: "Agradecido", french: "Avec gratitude", arabic: "بامتنان", dutch: "Dankbaar", time: 240 },
            { finnish: "Avoimin sydämin", english: "With an open heart", spanish: "Con el corazón abierto", french: "Avec un cœur ouvert", arabic: "بقلب مفتوح", dutch: "Met een open hart", time: 245 },
            { finnish: "Kohti tulevaisuutta", english: "Towards the future", spanish: "Hacia el futuro", french: "Vers l'avenir", arabic: "نحو المستقبل", dutch: "Naar de toekomst", time: 250 }
        ]
    },
    {
        id: 6,
        title: "Unelmien maailma",
        artist: "Sofia Manner",
        year: 2018,
        level: "advanced",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
        lyrics: [
            { finnish: "Unelmien maailmassa vaeltaen", english: "Wandering in the world of dreams", time: 0 },
            { finnish: "Todellisuus hämärtyy", english: "Reality blurs", time: 5 },
            { finnish: "Mielikuvitus lentää vapaana", english: "Imagination flies free", time: 10 },
            { finnish: "Rajattomat mahdollisuudet avautuvat", english: "Limitless possibilities open up", time: 15 },
            { finnish: "Luon oman todellisuuteni", english: "I create my own reality", time: 20 },
            { finnish: "Missä mikään ei ole mahdotonta", english: "Where nothing is impossible", time: 25 },
            { finnish: "Unelmat voivat toteutua", english: "Dreams can come true", time: 30 },
            { finnish: "Jos vain uskallan uskoa", english: "If I only dare to believe", time: 35 },
            { finnish: "Silmät kiinni, mieli auki", english: "Eyes closed, mind open", time: 40 },
            { finnish: "Uppoudun syvyyksiin", english: "I dive into the depths", time: 45 },
            { finnish: "Oman tietoisuuteni", english: "Of my own consciousness", time: 50 },
            { finnish: "Löydän maailman sisältäni", english: "I find a world within me", time: 55 },
            { finnish: "Täynnä värejä ja ääniä", english: "Full of colors and sounds", time: 60 },
            { finnish: "Joita en ole koskaan nähnyt", english: "That I've never seen before", time: 65 },
            { finnish: "Unien kieli on symbolinen", english: "The language of dreams is symbolic", time: 70 },
            { finnish: "Metaforat elävät omaa elämäänsä", english: "Metaphors live their own life", time: 75 },
            { finnish: "Lennan yli vuorten", english: "I fly over mountains", time: 80 },
            { finnish: "Sukellан valtamerten syvyyksiin", english: "I dive into ocean depths", time: 85 },
            { finnish: "Puhun eläinten kanssa", english: "I speak with animals", time: 90 },
            { finnish: "Ymmärrän kasvien kielen", english: "I understand the language of plants", time: 95 },
            { finnish: "Aikaja avaruus sulautuvat", english: "Time and space merge", time: 100 },
            { finnish: "Menneisyys ja tulevaisuus kohtaavat", english: "Past and future meet", time: 105 },
            { finnish: "Nykyhetkessä", english: "In the present moment", time: 110 },
            { finnish: "Joka on ikuinen", english: "Which is eternal", time: 115 },
            { finnish: "Unelmat kertovat totuuksia", english: "Dreams tell truths", time: 120 },
            { finnish: "Joita päivällä emme näe", english: "That we don't see during the day", time: 125 },
            { finnish: "Ne paljastavat pelkomme", english: "They reveal our fears", time: 130 },
            { finnish: "Ja syvimmät toiveemme", english: "And our deepest wishes", time: 135 },
            { finnish: "Alitajunta kommunikoi", english: "The subconscious communicates", time: 140 },
            { finnish: "Kuvien ja tunteiden kautta", english: "Through images and feelings", time: 145 },
            { finnish: "Unes sa tapaan ihmisiä", english: "In dreams I meet people", time: 150 },
            { finnish: "Joita en tunne", english: "Whom I don't know", time: 155 },
            { finnish: "Mutta jotka tuntuvat tutuilta", english: "But who feel familiar", time: 160 },
            { finnish: "Kuin he olisivat aina olleet siellä", english: "As if they've always been there", time: 165 },
            { finnish: "Odottamassa", english: "Waiting", time: 170 },
            { finnish: "Sisimmässäni", english: "Deep inside me", time: 175 },
            { finnish: "Herään aamuun", english: "I wake to morning", time: 180 },
            { finnish: "Unelma haalistuu", english: "The dream fades", time: 185 },
            { finnish: "Mutta jotain jää", english: "But something remains", time: 190 },
            { finnish: "Tunne, muisto, aavistus", english: "A feeling, a memory, a hunch", time: 195 },
            { finnish: "Jotain tärkeää", english: "Something important", time: 200 },
            { finnish: "Jonka pitäisi muistaa", english: "That I should remember", time: 205 },
            { finnish: "Kirjoitan sen ylös", english: "I write it down", time: 210 },
            { finnish: "Ennen kuin se katoaa", english: "Before it disappears", time: 215 },
            { finnish: "Kokonaan", english: "Completely", time: 220 },
            { finnish: "Unelmien maailma kutsuu", english: "The world of dreams calls", time: 225 },
            { finnish: "Joka yö", english: "Every night", time: 230 },
            { finnish: "Ja minä vastaan", english: "And I answer", time: 235 },
            { finnish: "Palaan sinne", english: "I return there", time: 240 },
            { finnish: "Kerta toisensa jälkeen", english: "Time after time", time: 245 },
            { finnish: "Tutkimaan", english: "To explore", time: 250 },
            { finnish: "Oppimaan", english: "To learn", time: 255 },
            { finnish: "Kasvamaan", english: "To grow", time: 260 }
        ]
    },
    {
        id: 7,
        title: "Aurinko paistaa",
        artist: "Liisa Nieminen",
        year: 2020,
        level: "beginner",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
        lyrics: [
            { finnish: "Aurinko paistaa taivaalla", english: "The sun shines in the sky", spanish: "El sol brilla en el cielo", french: "Le soleil brille dans le ciel", arabic: "الشمس تشرق في السماء", dutch: "De zon schijnt aan de hemel", time: 0 },
            { finnish: "Linnut laulavat puissa", english: "Birds sing in the trees", spanish: "Los pájaros cantan en los árboles", french: "Les oiseaux chantent dans les arbres", arabic: "الطيور تغني في الأشجار", dutch: "Vogels zingen in de bomen", time: 7 },
            { finnish: "Kesä on täällä taas", english: "Summer is here again", spanish: "El verano está aquí de nuevo", french: "L'été est de retour", arabic: "الصيف هنا مرة أخرى", dutch: "Zomer is er weer", time: 14 },
            { finnish: "Onnellinen olen nyt", english: "I am happy now", spanish: "Soy feliz ahora", french: "Je suis heureux maintenant", arabic: "أنا سعيد الآن", dutch: "Ik ben nu gelukkig", time: 21 },
            { finnish: "Lämpö tuntuu ihollani", english: "Warmth feels on my skin", spanish: "El calor se siente en mi piel", french: "La chaleur se sent sur ma peau", arabic: "الدفء يُشعر على جلدي", dutch: "Warmte voelt op mijn huid", time: 28 },
            { finnish: "Kukat kukkivat kauniisti", english: "Flowers bloom beautifully", spanish: "Las flores florecen bellamente", french: "Les fleurs fleurissent magnifiquement", arabic: "الزهور تتفتح بجمال", dutch: "Bloemen bloeien prachtig", time: 35 },
            { finnish: "Haluan nauttia tästä hetkestä", english: "I want to enjoy this moment", spanish: "Quiero disfrutar este momento", french: "Je veux profiter de ce moment", arabic: "أريد الاستمتاع بهذه اللحظة", dutch: "Ik wil van dit moment genieten", time: 42 },
            { finnish: "Kesä on paras vuodenaika", english: "Summer is the best season", spanish: "El verano es la mejor estación", french: "L'été est la meilleure saison", arabic: "الصيف هو أفضل موسم", dutch: "Zomer is het beste seizoen", time: 49 },
            { finnish: "Lapset leikkivät ulkona", english: "Children play outside", spanish: "Los niños juegan afuera", french: "Les enfants jouent dehors", arabic: "الأطفال يلعبون في الخارج", dutch: "Kinderen spelen buiten", time: 56 },
            { finnish: "Nauravat ja juoksevat", english: "They laugh and run", spanish: "Ríen y corren", french: "Ils rient et courent", arabic: "يضحكون ويركضون", dutch: "Ze lachen en rennen", time: 63 }
        ]
    },
    {
        id: 10,
        title: "Pieni talo",
        artist: "Jukka Lahtinen",
        year: 2019,
        level: "beginner",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        lyrics: [
            { finnish: "Pieni talo metsässä", english: "Small house in the forest", spanish: "Pequeña casa en el bosque", french: "Petite maison dans la forêt", arabic: "منزل صغير في الغابة", dutch: "Klein huis in het bos", time: 0 },
            { finnish: "Siellä asun yksin", english: "There I live alone", spanish: "Allí vivo solo", french: "Là je vis seul", arabic: "هناك أعيش وحيداً", dutch: "Daar woon ik alleen", time: 8 },
            { finnish: "Rauhallinen ja hiljainen", english: "Peaceful and quiet", spanish: "Pacífico y tranquilo", french: "Paisible et calme", arabic: "هادئ وساكن", dutch: "Vredig en stil", time: 16 },
            { finnish: "Täällä on hyvä olla", english: "It's good to be here", spanish: "Es bueno estar aquí", french: "C'est bon d'être ici", arabic: "من الجيد أن أكون هنا", dutch: "Het is goed om hier te zijn", time: 24 },
            { finnish: "Aamulla herään linnuille", english: "In the morning I wake to birds", spanish: "Por la mañana me despierto con pájaros", french: "Le matin je me réveille avec les oiseaux", arabic: "في الصباح أستيقظ على الطيور", dutch: "In de ochtend word ik wakker door vogels", time: 32 },
            { finnish: "Illalla katson auringonlaskua", english: "In the evening I watch the sunset", spanish: "Por la tarde veo la puesta de sol", french: "Le soir je regarde le coucher du soleil", arabic: "في المساء أشاهد غروب الشمس", dutch: "In de avond kijk ik naar de zonsondergang", time: 40 },
            { finnish: "Tämä on minun paikkani", english: "This is my place", spanish: "Este es mi lugar", french: "C'est mon endroit", arabic: "هذا مكاني", dutch: "Dit is mijn plek", time: 48 },
            { finnish: "Täällä tunnen oloni kotoisaksi", english: "Here I feel at home", spanish: "Aquí me siento en casa", french: "Ici je me sens chez moi", arabic: "هنا أشعر بأنني في بيتي", dutch: "Hier voel ik me thuis", time: 56 },
            { finnish: "Luonto ympärilläni", english: "Nature around me", spanish: "Naturaleza a mi alrededor", french: "La nature autour de moi", arabic: "الطبيعة حولي", dutch: "Natuur om me heen", time: 64 },
            { finnish: "Pieni talo, suuri rauha", english: "Small house, great peace", spanish: "Pequeña casa, gran paz", french: "Petite maison, grande paix", arabic: "منزل صغير، سلام عظيم", dutch: "Klein huis, grote vrede", time: 72 }
        ]
    },
    {
        id: 11,
        title: "Ystävä",
        artist: "Kaisa Mäkelä",
        year: 2021,
        level: "beginner",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        lyrics: [
            { finnish: "Sinä olet hyvä ystävä", english: "You are a good friend", spanish: "Eres un buen amigo", french: "Tu es un bon ami", arabic: "أنت صديق جيد", dutch: "Je bent een goede vriend", time: 0 },
            { finnish: "Aina vierelläni", english: "Always by my side", spanish: "Siempre a mi lado", french: "Toujours à mes côtés", arabic: "دائماً بجانبي", dutch: "Altijd aan mijn zijde", time: 7 },
            { finnish: "Kun tarvitsen apua", english: "When I need help", spanish: "Cuando necesito ayuda", french: "Quand j'ai besoin d'aide", arabic: "عندما أحتاج للمساعدة", dutch: "Wanneer ik hulp nodig heb", time: 14 },
            { finnish: "Olet siellä minua varten", english: "You are there for me", spanish: "Estás ahí para mí", french: "Tu es là pour moi", arabic: "أنت هناك من أجلي", dutch: "Ben je er voor mij", time: 21 },
            { finnish: "Nauramme yhdessä", english: "We laugh together", spanish: "Reímos juntos", french: "Nous rions ensemble", arabic: "نضحك معاً", dutch: "We lachen samen", time: 28 },
            { finnish: "Joskus myös itken", english: "Sometimes I also cry", spanish: "A veces también lloro", french: "Parfois je pleure aussi", arabic: "أحياناً أبكي أيضاً", dutch: "Soms huil ik ook", time: 35 },
            { finnish: "Mutta sinä ymmärrät", english: "But you understand", spanish: "Pero tú entiendes", french: "Mais tu comprends", arabic: "لكنك تفهم", dutch: "Maar jij begrijpt het", time: 42 },
            { finnish: "Kiitos että olet olemassa", english: "Thank you for existing", spanish: "Gracias por existir", french: "Merci d'exister", arabic: "شكراً لوجودك", dutch: "Bedankt dat je bestaat", time: 49 },
            { finnish: "Ystävyys on tärkeää", english: "Friendship is important", spanish: "La amistad es importante", french: "L'amitié est importante", arabic: "الصداقة مهمة", dutch: "Vriendschap is belangrijk", time: 56 },
            { finnish: "Sinä olet kultaa kalliimpi", english: "You are more precious than gold", spanish: "Eres más valioso que el oro", french: "Tu es plus précieux que l'or", arabic: "أنت أثمن من الذهب", dutch: "Je bent kostbaarder dan goud", time: 63 }
        ]
    },
    {
        id: 12,
        title: "Koira ja kissa",
        artist: "Pekka Virtanen",
        year: 2017,
        level: "beginner",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
        lyrics: [
            { finnish: "Minulla on koira", english: "I have a dog", spanish: "Tengo un perro", french: "J'ai un chien", arabic: "لدي كلب", dutch: "Ik heb een hond", time: 0 },
            { finnish: "Ja myös kissa", english: "And also a cat", spanish: "Y también un gato", french: "Et aussi un chat", arabic: "وأيضاً قطة", dutch: "En ook een kat", time: 7 },
            { finnish: "He ovat ystäviä", english: "They are friends", spanish: "Son amigos", french: "Ils sont amis", arabic: "هم أصدقاء", dutch: "Ze zijn vrienden", time: 14 },
            { finnish: "Leikkivät yhdessä", english: "They play together", spanish: "Juegan juntos", french: "Ils jouent ensemble", arabic: "يلعبون معاً", dutch: "Ze spelen samen", time: 21 },
            { finnish: "Koira haukkuu", english: "The dog barks", spanish: "El perro ladra", french: "Le chien aboie", arabic: "الكلب ينبح", dutch: "De hond blaft", time: 28 },
            { finnish: "Kissa kehräätää", english: "The cat purrs", spanish: "El gato ronronea", french: "Le chat ronronne", arabic: "القطة تخرخر", dutch: "De kat spint", time: 35 },
            { finnish: "Molemmat ovat söpöjä", english: "Both are cute", spanish: "Ambos son lindos", french: "Les deux sont mignons", arabic: "كلاهما لطيف", dutch: "Beide zijn schattig", time: 42 },
            { finnish: "Rakastan heitä", english: "I love them", spanish: "Los amo", french: "Je les aime", arabic: "أحبهما", dutch: "Ik hou van ze", time: 49 },
            { finnish: "He tekevät minut onnelliseksi", english: "They make me happy", spanish: "Me hacen feliz", french: "Ils me rendent heureux", arabic: "يجعلونني سعيداً", dutch: "Ze maken me gelukkig", time: 56 },
            { finnish: "Joka päivä", english: "Every day", spanish: "Cada día", french: "Chaque jour", arabic: "كل يوم", dutch: "Elke dag", time: 63 }
        ]
    },
    {
        id: 8,
        title: "Sininen meri",
        artist: "Tuomas Rantanen",
        year: 2020,
        level: "intermediate",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
        lyrics: [
            { finnish: "Sininen meri aaltoilee", english: "The blue sea waves", spanish: "El mar azul ondula", french: "La mer bleue ondule", arabic: "البحر الأزرق يتموج", dutch: "De blauwe zee golft", time: 0 },
            { finnish: "Purjevene liukuu hiljaa", english: "Sailboat glides quietly", spanish: "El velero se desliza en silencio", french: "Le voilier glisse silencieusement", arabic: "القارب الشراعي ينزلق بهدوء", dutch: "Zeilboot glijdt stil", time: 6 },
            { finnish: "Tuuli vie minut kauas", english: "Wind takes me far away", spanish: "El viento me lleva lejos", french: "Le vent m'emporte au loin", arabic: "الرياح تأخذني بعيداً", dutch: "De wind voert me ver weg", time: 12 },
            { finnish: "Vapaus on minun", english: "Freedom is mine", spanish: "La libertad es mía", french: "La liberté est mienne", arabic: "الحرية ملكي", dutch: "Vrijheid is van mij", time: 18 },
            { finnish: "Aaltojen ääni rauhoittaa", english: "Sound of waves calms", spanish: "El sonido de las olas calma", french: "Le bruit des vagues apaise", arabic: "صوت الأمواج يهدئ", dutch: "Het geluid van golven kalmeert", time: 24 },
            { finnish: "Horisontissa ei näy maata", english: "No land visible on horizon", spanish: "No hay tierra visible en el horizonte", french: "Aucune terre visible à l'horizon", arabic: "لا يمكن رؤية أرض في الأفق", dutch: "Geen land zichtbaar aan de horizon", time: 30 },
            { finnish: "Olen yksin mutta en yksinäinen", english: "I am alone but not lonely", spanish: "Estoy solo pero no solitario", french: "Je suis seul mais pas solitaire", arabic: "أنا وحيد لكن غير منعزل", dutch: "Ik ben alleen maar niet eenzaam", time: 36 },
            { finnish: "Meri on minun kotini", english: "The sea is my home", spanish: "El mar es mi hogar", french: "La mer est mon foyer", arabic: "البحر هو بيتي", dutch: "De zee is mijn thuis", time: 42 },
            { finnish: "Lokit lentävät yläpuolella", english: "Seagulls fly overhead", spanish: "Las gaviotas vuelan arriba", french: "Les mouettes volent au-dessus", arabic: "طيور النورس تحلق فوقنا", dutch: "Meeuwen vliegen boven", time: 48 },
            { finnish: "Niiden huudot kaikuvat", english: "Their cries echo", spanish: "Sus gritos resuenan", french: "Leurs cris résonnent", arabic: "صراخها يتردد صداه", dutch: "Hun kreten weergalmen", time: 54 },
            { finnish: "Aurinko laskee merelle", english: "Sun sets over the sea", spanish: "El sol se pone sobre el mar", french: "Le soleil se couche sur la mer", arabic: "الشمس تغرب فوق البحر", dutch: "De zon zakt over de zee", time: 60 },
            { finnish: "Taivas muuttuu punaiseksi", english: "Sky turns red", spanish: "El cielo se vuelve rojo", french: "Le ciel devient rouge", arabic: "السماء تصبح حمراء", dutch: "De hemel wordt rood", time: 66 },
            { finnish: "Oranssi ja violetti", english: "Orange and violet", spanish: "Naranja y violeta", french: "Orange et violet", arabic: "برتقالي وبنفسجي", dutch: "Oranje en violet", time: 72 },
            { finnish: "Värit tanssivat taivaalla", english: "Colors dance in the sky", spanish: "Los colores bailan en el cielo", french: "Les couleurs dansent dans le ciel", arabic: "الألوان ترقص في السماء", dutch: "Kleuren dansen aan de hemel", time: 78 },
            { finnish: "Vesi heijastaa kaiken", english: "Water reflects everything", spanish: "El agua refleja todo", french: "L'eau reflète tout", arabic: "الماء يعكس كل شيء", dutch: "Water weerspiegelt alles", time: 84 },
            { finnish: "Kaksinkertainen kauneus", english: "Double beauty", spanish: "Doble belleza", french: "Double beauté", arabic: "جمال مضاعف", dutch: "Dubbele schoonheid", time: 90 },
            { finnish: "Yö laskeutuu hitaasti", english: "Night descends slowly", spanish: "La noche desciende lentamente", french: "La nuit descend lentement", arabic: "الليل يهبط ببطء", dutch: "De nacht daalt langzaam", time: 96 },
            { finnish: "Tähdet alkavat loistaa", english: "Stars begin to shine", spanish: "Las estrellas comienzan a brillar", french: "Les étoiles commencent à briller", arabic: "النجوم تبدأ بالتألق", dutch: "Sterren beginnen te schijnen", time: 102 },
            { finnish: "Navigoin niiden avulla", english: "I navigate by them", spanish: "Navego por ellas", french: "Je navigue grâce à elles", arabic: "أبحر بواسطتها", dutch: "Ik navigeer ermee", time: 108 },
            { finnish: "Kuten merimiehet ennen", english: "Like sailors before", spanish: "Como los marineros antes", french: "Comme les marins avant", arabic: "مثل البحارة من قبل", dutch: "Zoals zeelieden voorheen", time: 114 },
            { finnish: "Vuosisatojen ajan", english: "For centuries", spanish: "Durante siglos", french: "Pendant des siècles", arabic: "لقرون", dutch: "Eeuwenlang", time: 120 },
            { finnish: "Meri kutsuu seikkailijoi ta", english: "Sea calls adventurers", spanish: "El mar llama a los aventureros", french: "La mer appelle les aventuriers", arabic: "البحر يدعو المغامرين", dutch: "De zee roept avonturiers", time: 126 },
            { finnish: "Rohkeita sieluja", english: "Brave souls", spanish: "Almas valientes", french: "Âmes courageuses", arabic: "نفوس شجاعة", dutch: "Dappere zielen", time: 132 },
            { finnish: "Jotka etsivät jotain enemmän", english: "Who seek something more", spanish: "Que buscan algo más", french: "Qui cherchent quelque chose de plus", arabic: "الذين يبحثون عن شيء أكثر", dutch: "Die iets meer zoeken", time: 138 },
            { finnish: "Kuin tavallinen elämä", english: "Than ordinary life", spanish: "Que la vida ordinaria", french: "Que la vie ordinaire", arabic: "من الحياة العادية", dutch: "Dan het gewone leven", time: 144 },
            { finnish: "Meri antaa vapauden", english: "Sea gives freedom", spanish: "El mar da libertad", french: "La mer donne la liberté", arabic: "البحر يمنح الحرية", dutch: "De zee geeft vrijheid", time: 150 },
            { finnish: "Mutta vaatii kunnioitusta", english: "But demands respect", spanish: "Pero exige respeto", french: "Mais exige le respect", arabic: "لكنه يطلب الاحترام", dutch: "Maar vereist respect", time: 156 },
            { finnish: "Se on voimakas ja arvaamaton", english: "It is powerful and unpredictable", spanish: "Es poderoso e impredecible", french: "Il est puissant et imprévisible", arabic: "إنه قوي ولا يمكن التنبؤ به", dutch: "Het is krachtig en onvoorspelbaar", time: 162 },
            { finnish: "Kaunis ja vaarallinen", english: "Beautiful and dangerous", spanish: "Hermoso y peligroso", french: "Beau et dangereux", arabic: "جميل وخطير", dutch: "Mooi en gevaarlijk", time: 168 },
            { finnish: "Rakastan sitä kaikesta huolimatta", english: "I love it nonetheless", spanish: "Lo amo a pesar de todo", french: "Je l'aime malgré tout", arabic: "أحبه على الرغم من كل شيء", dutch: "Ik hou ervan ondanks alles", time: 174 }
        ]
    },
    {
        id: 13,
        title: "Talven tarina",
        artist: "Laura Nieminen",
        year: 2021,
        level: "intermediate",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        lyrics: [
            { finnish: "Lumi peittää kaiken valkoiseksi", english: "Snow covers everything white", spanish: "La nieve cubre todo de blanco", french: "La neige couvre tout en blanc", arabic: "الثلج يغطي كل شيء بالأبيض", dutch: "Sneeuw bedekt alles wit", time: 0 },
            { finnish: "Hiljainen ja kaunis talvimaa", english: "Silent and beautiful winter land", spanish: "Tierra invernal silenciosa y hermosa", french: "Terre hivernale silencieuse et belle", arabic: "أرض شتوية صامتة وجميلة", dutch: "Stil en mooi winterlandschap", time: 6 },
            { finnish: "Pakkanen puree poskia", english: "Frost bites the cheeks", spanish: "La escarcha muerde las mejillas", french: "Le gel mord les joues", arabic: "الصقيع يلدغ الخدود", dutch: "Vorst bijt in de wangen", time: 12 },
            { finnish: "Mutta sydämeni on lämmin", english: "But my heart is warm", spanish: "Pero mi corazón está cálido", french: "Mais mon cœur est chaud", arabic: "لكن قلبي دافئ", dutch: "Maar mijn hart is warm", time: 18 },
            { finnish: "Lapset rakentavat lumiukkoja", english: "Children build snowmen", spanish: "Los niños construyen muñecos de nieve", french: "Les enfants construisent des bonshommes de neige", arabic: "الأطفال يبنون رجال الثلج", dutch: "Kinderen bouwen sneeuwpoppen", time: 24 },
            { finnish: "Laskevat mäkeä pulkalla", english: "Sled down the hill", spanish: "Deslizan por la colina en trineo", french: "Descendent la colline en luge", arabic: "ينزلقون على التل بالزلاجة", dutch: "Sleeën de heuvel af", time: 30 },
            { finnish: "Nauru täyttää ilman", english: "Laughter fills the air", spanish: "La risa llena el aire", french: "Le rire remplit l'air", arabic: "الضحك يملأ الهواء", dutch: "Gelach vult de lucht", time: 36 },
            { finnish: "Talvi on iloinen aika", english: "Winter is a joyful time", spanish: "El invierno es una época alegre", french: "L'hiver est une période joyeuse", arabic: "الشتاء وقت سعيد", dutch: "Winter is een vrolijke tijd", time: 42 },
            { finnish: "Illalla sytän kynttilöitä", english: "In the evening I light candles", spanish: "Por la tarde enciendo velas", french: "Le soir j'allume des bougies", arabic: "في المساء أشعل الشموع", dutch: "'s Avonds steek ik kaarsen aan", time: 48 },
            { finnish: "Istun takkatulen ääressä", english: "I sit by the fireplace", spanish: "Me siento junto a la chimenea", french: "Je m'assieds près de la cheminée", arabic: "أجلس بجانب المدفأة", dutch: "Ik zit bij de open haard", time: 54 },
            { finnish: "Luen hyvää kirjaa", english: "I read a good book", spanish: "Leo un buen libro", french: "Je lis un bon livre", arabic: "أقرأ كتاباً جيداً", dutch: "Ik lees een goed boek", time: 60 },
            { finnish: "Juon kuumaa kaakaota", english: "I drink hot cocoa", spanish: "Bebo cacao caliente", french: "Je bois du cacao chaud", arabic: "أشرب الكاكاو الساخن", dutch: "Ik drink warme chocolademelk", time: 66 },
            { finnish: "Ulkona on pimeää ja kylmää", english: "Outside it's dark and cold", spanish: "Afuera está oscuro y frío", french: "Dehors il fait sombre et froid", arabic: "في الخارج مظلم وبارد", dutch: "Buiten is het donker en koud", time: 72 },
            { finnish: "Mutta täällä sisällä on kodikasta", english: "But here inside it's cozy", spanish: "Pero aquí adentro es acogedor", french: "Mais ici à l'intérieur c'est confortable", arabic: "لكن هنا في الداخل مريح", dutch: "Maar hier binnen is het gezellig", time: 78 },
            { finnish: "Revontulet tanssivat taivaalla", english: "Northern lights dance in the sky", spanish: "Las auroras boreales bailan en el cielo", french: "Les aurores boréales dansent dans le ciel", arabic: "الشفق القطبي يرقص في السماء", dutch: "Noorderlicht danst aan de hemel", time: 84 },
            { finnish: "Vihreä valo liikkuu hitaasti", english: "Green light moves slowly", spanish: "La luz verde se mueve lentamente", french: "La lumière verte bouge lentement", arabic: "الضوء الأخضر يتحرك ببطء", dutch: "Groen licht beweegt langzaam", time: 90 },
            { finnish: "Se on luonnon magia", english: "It's nature's magic", spanish: "Es la magia de la naturaleza", french: "C'est la magie de la nature", arabic: "إنها سحر الطبيعة", dutch: "Het is de magie van de natuur", time: 96 },
            { finnish: "Jota vain pohjoisessa nähdään", english: "That's only seen in the north", spanish: "Que solo se ve en el norte", french: "Qu'on ne voit que dans le nord", arabic: "التي تُرى فقط في الشمال", dutch: "Die alleen in het noorden te zien is", time: 102 },
            { finnish: "Talvi opettaa kärsivällisyyttä", english: "Winter teaches patience", spanish: "El invierno enseña paciencia", french: "L'hiver enseigne la patience", arabic: "الشتاء يعلم الصبر", dutch: "Winter leert geduld", time: 108 },
            { finnish: "Odottamaan kevättä", english: "To wait for spring", spanish: "A esperar la primavera", french: "À attendre le printemps", arabic: "انتظار الربيع", dutch: "Om te wachten op de lente", time: 114 },
            { finnish: "Mutta myös nauttimaan tästä hetkestä", english: "But also to enjoy this moment", spanish: "Pero también a disfrutar este momento", french: "Mais aussi à profiter de ce moment", arabic: "ولكن أيضاً للاستمتاع بهذه اللحظة", dutch: "Maar ook om van dit moment te genieten", time: 120 },
            { finnish: "Talven hiljaisuudesta ja rauhasta", english: "Of winter's silence and peace", spanish: "Del silencio y paz del invierno", french: "Du silence et de la paix de l'hiver", arabic: "من صمت وسلام الشتاء", dutch: "Van de stilte en vrede van de winter", time: 126 },
            { finnish: "Jokaisella vuodenajalla on tarkoitus", english: "Every season has a purpose", spanish: "Cada estación tiene un propósito", french: "Chaque saison a un but", arabic: "كل موسم له هدف", dutch: "Elk seizoen heeft een doel", time: 132 },
            { finnish: "Talvi antaa aikaa pysähtyä", english: "Winter gives time to stop", spanish: "El invierno da tiempo para detenerse", french: "L'hiver donne le temps de s'arrêter", arabic: "الشتاء يعطي وقتاً للتوقف", dutch: "Winter geeft tijd om te stoppen", time: 138 },
            { finnish: "Miettiä ja levätä", english: "To think and rest", spanish: "Para pensar y descansar", french: "Pour réfléchir et se reposer", arabic: "للتفكير والراحة", dutch: "Om na te denken en te rusten", time: 144 },
            { finnish: "Valmistautua uuteen alkuun", english: "To prepare for a new beginning", spanish: "Para prepararse para un nuevo comienzo", french: "Pour préparer un nouveau départ", arabic: "للاستعداد لبداية جديدة", dutch: "Om je voor te bereiden op een nieuw begin", time: 150 },
            { finnish: "Kun kevät lopulta saapuu", english: "When spring finally arrives", spanish: "Cuando finalmente llega la primavera", french: "Quand le printemps arrive enfin", arabic: "عندما يأتي الربيع أخيراً", dutch: "Wanneer de lente eindelijk komt", time: 156 },
            { finnish: "Olemme valmiita", english: "We are ready", spanish: "Estamos listos", french: "Nous sommes prêts", arabic: "نحن مستعدون", dutch: "Zijn we klaar", time: 162 },
            { finnish: "Kiitollisia talvesta", english: "Grateful for winter", spanish: "Agradecidos por el invierno", french: "Reconnaissants pour l'hiver", arabic: "ممتنون للشتاء", dutch: "Dankbaar voor de winter", time: 168 },
            { finnish: "Ja sen antamista lahjoista", english: "And its gifts", spanish: "Y sus regalos", french: "Et ses cadeaux", arabic: "وهداياه", dutch: "En zijn geschenken", time: 174 }
        ]
    },
    {
        id: 9,
        title: "Tähtitaivas",
        artist: "Jari Koskinen",
        year: 2019,
        level: "advanced",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
        lyrics: [
            { finnish: "Tähtitaivas loistaa yllä", english: "Starry sky shines above", spanish: "El cielo estrellado brilla arriba", french: "Le ciel étoilé brille au-dessus", arabic: "السماء المرصعة بالنجوم تشرق في الأعلى", time: 0 },
            { finnish: "Kuu valaisee polkuni", english: "Moon illuminates my path", spanish: "La luna ilumina mi camino", french: "La lune illumine mon chemin", arabic: "القمر ينير طريقي", time: 5 },
            { finnish: "Äärettömyys ympäröi minua", english: "Infinity surrounds me", spanish: "La infinidad me rodea", french: "L'infini m'entoure", arabic: "اللانهاية تحيط بي", time: 10 },
            { finnish: "Löydän rauhan syvällä sisimmässäni", english: "I find peace deep within myself", spanish: "Encuentro paz en lo profundo de mí", french: "Je trouve la paix au plus profond de moi", arabic: "أجد السلام في أعماقي", time: 15 },
            { finnish: "Tähdet kertovat tarinoita", english: "Stars tell stories", spanish: "Las estrellas cuentan historias", french: "Les étoiles racontent des histoires", arabic: "النجوم تروي قصصاً", time: 20 },
            { finnish: "Universumin salaisuuksista", english: "About secrets of the universe", spanish: "Sobre secretos del universo", french: "Sur les secrets de l'univers", arabic: "عن أسرار الكون", time: 25 },
            { finnish: "Tunnen olevani osa jotain suurempaa", english: "I feel part of something greater", spanish: "Siento ser parte de algo más grande", french: "Je me sens partie de quelque chose de plus grand", arabic: "أشعر بأنني جزء من شيء أعظم", time: 30 },
            { finnish: "Yö antaa minulle perspektiivin", english: "Night gives me perspective", spanish: "La noche me da perspectiva", french: "La nuit me donne de la perspective", arabic: "الليل يعطيني منظوراً", time: 35 },
            { finnish: "Galaksit pyörivät pimeydessä", english: "Galaxies spin in the darkness", spanish: "Las galaxias giran en la oscuridad", french: "Les galaxies tournent dans l'obscurité", arabic: "المجرات تدور في الظلام", time: 40 },
            { finnish: "Miljoonien valovuosien päässä", english: "Millions of light years away", spanish: "A millones de años luz de distancia", french: "À des millions d'années-lumière", arabic: "على بُعد ملايين السنين الضوئية", time: 45 },
            { finnish: "Silti näen niiden valon", english: "Yet I see their light", spanish: "Sin embargo veo su luz", french: "Pourtant je vois leur lumière", arabic: "ومع ذلك أرى ضوءها", time: 50 },
            { finnish: "Tänä yönä täällä Maassa", english: "Tonight here on Earth", spanish: "Esta noche aquí en la Tierra", french: "Ce soir ici sur Terre", arabic: "الليلة هنا على الأرض", time: 55 },
            { finnish: "Olemme kaikki tähtipölyä", english: "We are all stardust", spanish: "Todos somos polvo de estrellas", french: "Nous sommes tous de la poussière d'étoiles", arabic: "كلنا غبار نجوم", time: 60 },
            { finnish: "Syntyneet samasta alkuräjähdyksestä", english: "Born from the same Big Bang", spanish: "Nacidos del mismo Big Bang", french: "Nés du même Big Bang", arabic: "وُلدنا من نفس الانفجار العظيم", time: 65 },
            { finnish: "Yhdistyneitä kaikkien kanssa", english: "Connected with everyone", spanish: "Conectados con todos", french: "Connectés avec tout le monde", arabic: "متصلون مع الجميع", time: 70 },
            { finnish: "Ja kaiken kanssa", english: "And with everything", spanish: "Y con todo", french: "Et avec tout", arabic: "ومع كل شيء", time: 75 },
            { finnish: "Tähtitieteen kautta", english: "Through astronomy", spanish: "A través de la astronomía", french: "À travers l'astronomie", arabic: "من خلال علم الفلك", time: 80 },
            { finnish: "Ymmärrän paikkani", english: "I understand my place", spanish: "Entiendo mi lugar", french: "Je comprends ma place", arabic: "أفهم مكاني", time: 85 },
            { finnish: "Tässä valtavassa kosmoksessa", english: "In this vast cosmos", spanish: "En este vasto cosmos", french: "Dans ce vaste cosmos", arabic: "في هذا الكون الشاسع", time: 90 },
            { finnish: "Pieni mutta merkityksellinen", english: "Small but meaningful", spanish: "Pequeño pero significativo", french: "Petit mais significatif", arabic: "صغير لكن ذو معنى", time: 95 },
            { finnish: "Osa suurempaa kokonaisuutta", english: "Part of a greater whole", spanish: "Parte de un todo mayor", french: "Partie d'un tout plus grand", arabic: "جزء من كل أعظم", time: 100 },
            { finnish: "Pohjoistähti ohjaa minua", english: "North Star guides me", spanish: "La Estrella del Norte me guía", french: "L'étoile du Nord me guide", arabic: "نجم الشمال يرشدني", time: 105 },
            { finnish: "Orion metsästää taivaalla", english: "Orion hunts in the sky", spanish: "Orión caza en el cielo", french: "Orion chasse dans le ciel", arabic: "الجبار يصطاد في السماء", time: 110 },
            { finnish: "Suuret ja pienet karhut", english: "Big and Little Dipper", spanish: "Osa Mayor y Menor", french: "Grande et Petite Ourse", arabic: "الدب الأكبر والأصغر", time: 115 },
            { finnish: "Kierrävät napaa", english: "Circle the pole", spanish: "Giran alrededor del polo", french: "Tournent autour du pôle", arabic: "يدوران حول القطب", time: 120 },
            { finnish: "Tähtikuviot kertovat aikaa", english: "Constellations tell time", spanish: "Las constelaciones marcan el tiempo", french: "Les constellations indiquent le temps", arabic: "الأبراج تخبر الوقت", time: 125 },
            { finnish: "Vuodenaikojen vaihtumista", english: "The changing of seasons", spanish: "El cambio de las estaciones", french: "Le changement des saisons", arabic: "تغير الفصول", time: 130 },
            { finnish: "Elämän sykliä", english: "The cycle of life", spanish: "El ciclo de la vida", french: "Le cycle de la vie", arabic: "دورة الحياة", time: 135 },
            { finnish: "Revontulet tanssivat pohjoisessa", english: "Northern lights dance in the north", spanish: "Las auroras boreales bailan en el norte", french: "Les aurores boréales dansent au nord", arabic: "الشفق القطبي يرقص في الشمال", time: 140 },
            { finnish: "Vihreä, sininen, punainen", english: "Green, blue, red", spanish: "Verde, azul, rojo", french: "Vert, bleu, rouge", arabic: "أخضر، أزرق، أحمر", time: 145 },
            { finnish: "Luonnon valoshow", english: "Nature's light show", spanish: "El espectáculo de luces de la naturaleza", french: "Le spectacle de lumière de la nature", arabic: "عرض الأضواء الطبيعي", time: 150 },
            { finnish: "Henkeäsalpaavan kaunis", english: "Breathtakingly beautiful", spanish: "Impresionantemente hermoso", french: "À couper le souffle", arabic: "جميل بشكل يخطف الأنفاس", time: 155 },
            { finnish: "Tähtiputoukset vilahtavat", english: "Shooting stars flash", spanish: "Las estrellas fugaces destellan", french: "Les étoiles filantes brillent", arabic: "الشهب تومض", time: 160 },
            { finnish: "Teen toiveen", english: "I make a wish", spanish: "Pido un deseo", french: "Je fais un vœu", arabic: "أتمنى أمنية", time: 165 },
            { finnish: "Ehkä se toteutuu", english: "Maybe it will come true", spanish: "Quizás se haga realidad", french: "Peut-être se réalisera-t-il", arabic: "ربما تتحقق", time: 170 },
            { finnish: "Ehkä ei", english: "Maybe not", spanish: "Quizás no", french: "Peut-être pas", arabic: "ربما لا", time: 175 },
            { finnish: "Mutta toivo elää", english: "But hope lives", spanish: "Pero la esperanza vive", french: "Mais l'espoir vit", arabic: "لكن الأمل يعيش", time: 180 },
            { finnish: "Samoin kuin minä", english: "As do I", spanish: "Como yo", french: "Comme moi", arabic: "مثلي تماماً", time: 185 },
            { finnish: "Tässä hetkessä", english: "In this moment", spanish: "En este momento", french: "En ce moment", arabic: "في هذه اللحظة", time: 190 },
            { finnish: "Tähtitaivaan alla", english: "Under the starry sky", spanish: "Bajo el cielo estrellado", french: "Sous le ciel étoilé", arabic: "تحت السماء المرصعة بالنجوم", time: 195 },
            { finnish: "Tunnen olevani elossa", english: "I feel alive", spanish: "Me siento vivo", french: "Je me sens vivant", arabic: "أشعر بأنني حي", time: 200 },
            { finnish: "Tunnen olevani yhteydessä", english: "I feel connected", spanish: "Me siento conectado", french: "Je me sens connecté", arabic: "أشعر بأنني متصل", time: 205 },
            { finnish: "Kaikkeen mikä on", english: "To all that is", spanish: "Con todo lo que es", french: "À tout ce qui est", arabic: "بكل ما هو موجود", time: 210 },
            { finnish: "Mikä on ollut", english: "That has been", spanish: "Lo que ha sido", french: "Ce qui a été", arabic: "ما كان موجوداً", time: 215 },
            { finnish: "Ja mikä tulee olemaan", english: "And that will be", spanish: "Y lo que será", french: "Et ce qui sera", arabic: "وما سيكون", time: 220 },
            { finnish: "Ikuisuus avautuu", english: "Eternity unfolds", spanish: "La eternidad se despliega", french: "L'éternité se déploie", arabic: "الأبدية تتكشف", time: 225 },
            { finnish: "Yön hiljaisuudessa", english: "In the silence of night", spanish: "En el silencio de la noche", french: "Dans le silence de la nuit", arabic: "في صمت الليل", time: 230 },
            { finnish: "Ja minä kuuntelen", english: "And I listen", spanish: "Y yo escucho", french: "Et j'écoute", arabic: "وأنا أستمع", time: 235 },
            { finnish: "Tähtien kuiskauksia", english: "To the whispers of stars", spanish: "Los susurros de las estrellas", french: "Aux chuchotements des étoiles", arabic: "لهمسات النجوم", time: 240 },
            { finnish: "Universumin laulua", english: "To the song of the universe", spanish: "La canción del universo", french: "Au chant de l'univers", arabic: "لأغنية الكون", time: 245 },
            { finnish: "Joka kaikuu", english: "That echoes", spanish: "Que resuena", french: "Qui résonne", arabic: "التي تتردد", time: 250 },
            { finnish: "Läpi ajan ja avaruuden", english: "Through time and space", spanish: "A través del tiempo y el espacio", french: "À travers le temps et l'espace", arabic: "عبر الزمان والمكان", time: 255 },
            { finnish: "Ikuisesti", english: "Forever", spanish: "Para siempre", french: "Pour toujours", arabic: "إلى الأبد", time: 260 }
        ]
    },
    {
        id: 14,
        title: "Metsän sydän",
        artist: "Veikko Aalto",
        year: 2022,
        level: "advanced",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
        lyrics: [
            { finnish: "Syvällä metsässä kävelen", english: "Deep in the forest I walk", time: 0 },
            { finnish: "Puiden juuret muodostavat verkoston", english: "Tree roots form a network", time: 5 },
            { finnish: "Näkymättömän yhteyden", english: "An invisible connection", time: 10 },
            { finnish: "Joka yhdistää kaiken elävän", english: "That connects all living things", time: 15 },
            { finnish: "Metsä hengittää minun kanssani", english: "The forest breathes with me", time: 20 },
            { finnish: "Happi ja hiilidioksidi vaihtuvat", english: "Oxygen and carbon dioxide exchange", time: 25 },
            { finnish: "Symbioottisessa tanssissa", english: "In a symbiotic dance", time: 30 },
            { finnish: "Joka on jatkunut miljoonien vuosien ajan", english: "That has continued for millions of years", time: 35 },
            { finnish: "Sammalet peittävät kivet", english: "Mosses cover the stones", time: 40 },
            { finnish: "Vihreä vaippa kaiken päällä", english: "A green blanket over everything", time: 45 },
            { finnish: "Sienet kasvavat pimeydessä", english: "Mushrooms grow in the darkness", time: 50 },
            { finnish: "Hajoittaen kuollutta ainesta", english: "Decomposing dead matter", time: 55 },
            { finnish: "Palauttaen ravinteita maaperään", english: "Returning nutrients to the soil", time: 60 },
            { finnish: "Kierto jatkuu loputtomiin", english: "The cycle continues endlessly", time: 65 },
            { finnish: "Kuolema ruokkii elämää", english: "Death feeds life", time: 70 },
            { finnish: "Elämä johtaa kuolemaan", english: "Life leads to death", time: 75 },
            { finnish: "Mutta mikään ei katoa", english: "But nothing disappears", time: 80 },
            { finnish: "Vain muuttaa muotoaan", english: "Only changes its form", time: 85 },
            { finnish: "Vanhat puut kaatuvat", english: "Old trees fall", time: 90 },
            { finnish: "Niiden lahopuu luo elinympäristöjä", english: "Their decaying wood creates habitats", time: 95 },
            { finnish: "Sadoille lajeille", english: "For hundreds of species", time: 100 },
            { finnish: "Hyönteiset, linnut, nisäkkäät", english: "Insects, birds, mammals", time: 105 },
            { finnish: "Kaikki riippuvaisia toisistaan", english: "All dependent on each other", time: 110 },
            { finnish: "Ruokakettju nivoutuu yhteen", english: "The food chain weaves together", time: 115 },
            { finnish: "Monimutkaiseksi kokonaisuudeksi", english: "Into a complex whole", time: 120 },
            { finnish: "Jonka jokainen osa on tärkeä", english: "Where every part is important", time: 125 },
            { finnish: "Kuulen pöllön huudon", english: "I hear the owl's call", time: 130 },
            { finnish: "Yöllinen metsästäjä liikkeellä", english: "Nocturnal hunter on the move", time: 135 },
            { finnish: "Hiljaiset siivet lentävät", english: "Silent wings fly", time: 140 },
            { finnish: "Saalistaa pimeydessä", english: "Hunting in the darkness", time: 145 },
            { finnish: "Metsän sydän sykkii", english: "The heart of the forest beats", time: 150 },
            { finnish: "Hitaasti mutta varmasti", english: "Slowly but surely", time: 155 },
            { finnish: "Vuodenajat vaihtelevat", english: "Seasons alternate", time: 160 },
            { finnish: "Mutta metsä pysyy", english: "But the forest remains", time: 165 },
            { finnish: "Vahva ja kestävä", english: "Strong and enduring", time: 170 },
            { finnish: "Selviytynyt jääkausista", english: "Survived ice ages", time: 175 },
            { finnish: "Tulipaloista ja myrskyistä", english: "Fires and storms", time: 180 },
            { finnish: "Metsä muistaa kaiken", english: "The forest remembers everything", time: 185 },
            { finnish: "Sen vuosirenkaissa lukee historia", english: "Its annual rings read history", time: 190 },
            { finnish: "Kuivat kesät ja kosteat talvet", english: "Dry summers and wet winters", time: 195 },
            { finnish: "Tuleen ja tuuleen", english: "Fire and wind", time: 200 },
            { finnish: "Kaikki jättää jälkensä", english: "Everything leaves its mark", time: 205 },
            { finnish: "Astun varovasti", english: "I step carefully", time: 210 },
            { finnish: "Kunnioittaen tätä pyhää paikkaa", english: "Respecting this sacred place", time: 215 },
            { finnish: "Metsä on temppeli", english: "The forest is a temple", time: 220 },
            { finnish: "Luonnon katedraali", english: "Nature's cathedral", time: 225 },
            { finnish: "Täällä löydän rauhan", english: "Here I find peace", time: 230 },
            { finnish: "Täällä ymmärrän paikkani", english: "Here I understand my place", time: 235 },
            { finnish: "Osana suurempaa kokonaisuutta", english: "As part of a greater whole", time: 240 },
            { finnish: "Metsä opettaa nöyryyttä", english: "The forest teaches humility", time: 245 },
            { finnish: "Ja yhteyttä", english: "And connection", time: 250 },
            { finnish: "Kaikkeen elämään", english: "To all life", time: 255 }
        ]
    },
    {
        id: 15,
        title: "Ajan virta",
        artist: "Martti Lehtonen",
        year: 2023,
        level: "advanced",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
        lyrics: [
            { finnish: "Aika virtaa kuin joki", english: "Time flows like a river", time: 0 },
            { finnish: "Ei koskaan pysähdy", english: "Never stops", time: 5 },
            { finnish: "Ei koskaan palaa taaksepäin", english: "Never goes back", time: 10 },
            { finnish: "Vain eteenpäin", english: "Only forward", time: 15 },
            { finnish: "Kohti tuntematonta", english: "Towards the unknown", time: 20 },
            { finnish: "Lapsuus tuntuu kaukaiselta muistolta", english: "Childhood feels like a distant memory", time: 25 },
            { finnish: "Vaikka eilen vasta oli", english: "Though it was just yesterday", time: 30 },
            { finnish: "Nuoruus haihtui huomaamatta", english: "Youth faded unnoticed", time: 35 },
            { finnish: "Aikuisuus tuli äkkiä", english: "Adulthood came suddenly", time: 40 },
            { finnish: "Vastuut ja velvollisuudet", english: "Responsibilities and duties", time: 45 },
            { finnish: "Täyttivät päivät", english: "Filled the days", time: 50 },
            { finnish: "Kiire vei mukanaan", english: "Hurry took away", time: 55 },
            { finnish: "Hetkiä joita en huomannut", english: "Moments I didn't notice", time: 60 },
            { finnish: "Koska odotin tulevaa", english: "Because I was waiting for the future", time: 65 },
            { finnish: "Mutta tulevaisuus on vain illuusio", english: "But the future is just an illusion", time: 70 },
            { finnish: "Kun se saapuu", english: "When it arrives", time: 75 },
            { finnish: "Se on nykyhetki", english: "It is the present moment", time: 80 },
            { finnish: "Ja nykyhetki on jo menneisyyttä", english: "And the present is already the past", time: 85 },
            { finnish: "Kun yritän tarttua siihen", english: "When I try to grasp it", time: 90 },
            { finnish: "Se luisuu sormieni välistä", english: "It slips between my fingers", time: 95 },
            { finnish: "Kuin hiekka", english: "Like sand", time: 100 },
            { finnish: "Kuin vesi", english: "Like water", time: 105 },
            { finnish: "Aika on arvoituksellinen", english: "Time is mysterious", time: 110 },
            { finnish: "Joskus se kulkee hitaasti", english: "Sometimes it moves slowly", time: 115 },
            { finnish: "Odottaessa tuntuu ikuisuudelta", english: "Waiting feels like eternity", time: 120 },
            { finnish: "Toisinaan se kiitää ohi", english: "Other times it rushes by", time: 125 },
            { finnish: "Iloiset hetket päättyvät liian nopeasti", english: "Happy moments end too quickly", time: 130 },
            { finnish: "Einsteinin mukaan aika on suhteellista", english: "According to Einstein time is relative", time: 135 },
            { finnish: "Riippuu havainnoijasta", english: "Depends on the observer", time: 140 },
            { finnish: "Nopeudesta ja painovoimasta", english: "Speed and gravity", time: 145 },
            { finnish: "Mutta minulle aika on kokemus", english: "But for me time is an experience", time: 150 },
            { finnish: "Subjektiivinen tunne", english: "A subjective feeling", time: 155 },
            { finnish: "Muistojen kerrostuma", english: "Layers of memories", time: 160 },
            { finnish: "Olen elänyt niin monta päivää", english: "I have lived so many days", time: 165 },
            { finnish: "Mutta muistan vain murto-osan", english: "But remember only a fraction", time: 170 },
            { finnish: "Tärkeitä hetkiä", english: "Important moments", time: 175 },
            { finnish: "Jotka määrittävät kuka olen", english: "That define who I am", time: 180 },
            { finnish: "Ensimmäinen koulupäivä", english: "First day of school", time: 185 },
            { finnish: "Ensimmäinen rakkaus", english: "First love", time: 190 },
            { finnish: "Ensimmäinen menetys", english: "First loss", time: 195 },
            { finnish: "Kaikki nämä hetket", english: "All these moments", time: 200 },
            { finnish: "Muodostavat tarinan", english: "Form a story", time: 205 },
            { finnish: "Minun tarinani", english: "My story", time: 210 },
            { finnish: "Ja tarina jatkuu", english: "And the story continues", time: 215 },
            { finnish: "Niin kauan kuin elän", english: "As long as I live", time: 220 },
            { finnish: "Joka päivä uusi luku", english: "Every day a new chapter", time: 225 },
            { finnish: "Kirjoitetaan yhdessä", english: "Written together", time: 230 },
            { finnish: "Ajan kanssa", english: "With time", time: 235 },
            { finnish: "Kumppanina joka ei koskaan jätä", english: "A partner who never leaves", time: 240 },
            { finnish: "Ajan virta vie minut", english: "The stream of time carries me", time: 245 },
            { finnish: "Kohti lopullista määränpäätä", english: "Towards the final destination", time: 250 },
            { finnish: "Mutta matka on elämä", english: "But the journey is life", time: 255 }
        ]
    },
    {
        id: 16,
        title: "Sisäinen matka",
        artist: "Aino Saari",
        year: 2024,
        level: "advanced",
        audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
        lyrics: [
            { finnish: "Sisäinen matka alkaa hiljaisuudessa", english: "The inner journey begins in silence", time: 0 },
            { finnish: "Kun ulkoiset äänet hiljenevät", english: "When external sounds quiet down", time: 5 },
            { finnish: "Kuulen oman ääneni", english: "I hear my own voice", time: 10 },
            { finnish: "Syvältä sisältäni", english: "From deep within", time: 15 },
            { finnish: "Se puhuu totuuksia", english: "It speaks truths", time: 20 },
            { finnish: "Joita en halua kuulla", english: "That I don't want to hear", time: 25 },
            { finnish: "Mutta jotka minun täytyy kohdata", english: "But that I must face", time: 30 },
            { finnish: "Kasvun edellytyksenä", english: "As a prerequisite for growth", time: 35 },
            { finnish: "Meditaatiossa uppoudun", english: "In meditation I immerse", time: 40 },
            { finnish: "Syvyyksiin oman mieleni", english: "Into the depths of my mind", time: 45 },
            { finnish: "Löydän kerroksia ja kerroksia", english: "I find layers and layers", time: 50 },
            { finnish: "Tietoisuutta ja tiedostamatonta", english: "Conscious and unconscious", time: 55 },
            { finnish: "Pelkoja ja toiveita", english: "Fears and hopes", time: 60 },
            { finnish: "Muistoja ja unelmia", english: "Memories and dreams", time: 65 },
            { finnish: "Kaikki sekoittuu yhteen", english: "Everything mixes together", time: 70 },
            { finnish: "Mutta hiljalleen selkenee", english: "But gradually becomes clear", time: 75 },
            { finnish: "Kun annan ajan", english: "When I give time", time: 80 },
            { finnish: "Ja tilaa", english: "And space", time: 85 },
            { finnish: "Prosessille joka ei kiirehdittävissä", english: "For a process that cannot be rushed", time: 90 },
            { finnish: "Itsetuntemus vaatii rohkeutta", english: "Self-knowledge requires courage", time: 95 },
            { finnish: "Katsoa peiliin", english: "To look in the mirror", time: 100 },
            { finnish: "Ilman maskeja", english: "Without masks", time: 105 },
            { finnish: "Ilman puolustusmekanismeja", english: "Without defense mechanisms", time: 110 },
            { finnish: "Vain olla", english: "Just to be", time: 115 },
            { finnish: "Aidosti oma itseni", english: "Truly myself", time: 120 },
            { finnish: "Hyväksyä vahvuudet", english: "Accept strengths", time: 125 },
            { finnish: "Ja heikkoudet", english: "And weaknesses", time: 130 },
            { finnish: "Valoa ja varjoa", english: "Light and shadow", time: 135 },
            { finnish: "Molemmat kuuluvat minuun", english: "Both belong to me", time: 140 },
            { finnish: "Tekevät minut kokonaiseksi", english: "Make me whole", time: 145 },
            { finnish: "Sisäinen lapsi huutaa huomiota", english: "The inner child cries for attention", time: 150 },
            { finnish: "Haavoittunut ja unohdetu", english: "Wounded and forgotten", time: 155 },
            { finnish: "Kaipaa rakkautta", english: "Longs for love", time: 160 },
            { finnish: "Hyväksyntää", english: "Acceptance", time: 165 },
            { finnish: "Annan sitä", english: "I give it", time: 170 },
            { finnish: "Itselleni", english: "To myself", time: 175 },
            { finnish: "Anteeksiantamus alkaa sisältä", english: "Forgiveness begins within", time: 180 },
            { finnish: "Ensin itselleni", english: "First to myself", time: 185 },
            { finnish: "Sitten muille", english: "Then to others", time: 190 },
            { finnish: "Vapautan vihan", english: "I release anger", time: 195 },
            { finnish: "Katkeruuden", english: "Bitterness", time: 200 },
            { finnish: "Katumus", english: "Regret", time: 205 },
            { finnish: "Ne painoivat liian kauan", english: "They weighed too long", time: 210 },
            { finnish: "Nyt päästän irti", english: "Now I let go", time: 215 },
            { finnish: "Uskon prosessiin", english: "I trust the process", time: 220 },
            { finnish: "Matkaan jolla ei ole päämäärää", english: "A journey with no destination", time: 225 },
            { finnish: "Vain jatkuva kasvu", english: "Only continuous growth", time: 230 },
            { finnish: "Kehitys", english: "Development", time: 235 },
            { finnish: "Tuleminen", english: "Becoming", time: 240 },
            { finnish: "Sisäinen matka ei lopu koskaan", english: "The inner journey never ends", time: 245 },
            { finnish: "Mutta siitä tulee helpompaa", english: "But it becomes easier", time: 250 },
            { finnish: "Kun oppin rakastamaan", english: "When I learn to love", time: 255 },
            { finnish: "Itseäni", english: "Myself", time: 260 }
        ]
    }
];

// Get all songs
function getAllSongs() {
    return songsDatabase;
}

// Get songs by level
function getSongsByLevel(level) {
    return songsDatabase.filter(song => song.level === level);
}

// Get random song
function getRandomSong() {
    const randomIndex = Math.floor(Math.random() * songsDatabase.length);
    return songsDatabase[randomIndex];
}

// Get song by ID
function getSongById(id) {
    return songsDatabase.find(song => song.id === parseInt(id));
}

// Get random song by level
function getRandomSongByLevel(level) {
    const levelSongs = getSongsByLevel(level);
    if (levelSongs.length === 0) return null;
    const randomIndex = Math.floor(Math.random() * levelSongs.length);
    return levelSongs[randomIndex];
}

// Search songs by title, artist, or year
function searchSongs(query) {
    if (!query) return getAllSongs();
    
    const lowerQuery = query.toLowerCase();
    return songsDatabase.filter(song => 
        song.title.toLowerCase().includes(lowerQuery) ||
        song.artist.toLowerCase().includes(lowerQuery) ||
        song.year.toString().includes(lowerQuery)
    );
}
